"""empty message

Revision ID: e2ea5be46bb1
Revises: 
Create Date: 2020-05-18 00:33:09.629542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ea5be46bb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escudo', sa.String(), nullable=True),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_times_nome'), 'times', ['nome'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('jogos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rodada', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('time_visitante_id', sa.Integer(), nullable=True),
    sa.Column('time_mandante_id', sa.Integer(), nullable=True),
    sa.Column('gols_mandante', sa.Integer(), nullable=True),
    sa.Column('gols_visitante', sa.Integer(), nullable=True),
    sa.Column('amarelos_mandante', sa.Integer(), nullable=True),
    sa.Column('amarelos_visitante', sa.Integer(), nullable=True),
    sa.Column('vermelhos_mandante', sa.Integer(), nullable=True),
    sa.Column('vermelhos_visitante', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['time_mandante_id'], ['times.id'], ),
    sa.ForeignKeyConstraint(['time_visitante_id'], ['times.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time_visitante_id', 'time_mandante_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogos')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_times_nome'), table_name='times')
    op.drop_table('times')
    # ### end Alembic commands ###
